# Use official base image of Java Runtim
FROM --platform=linux/arm64 openjdk:21-jdk-slim

# Set volume point to /tmp
VOLUME /tmp

# Make port 8099 available to the world outside container
EXPOSE 8099

# Set application's JAR file
ARG JAR_FILE=target/*.jar

# Add the application's JAR file to the container
ADD ${JAR_FILE} app.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app.jar"]